### ISSUE TITLE
ImportError: No module named 'discord'

### ISSUE THREAD

**Issue by deatcoca** [Gamerhythm/Discrimy#1]
I'm on Xubuntu 17.04 and when I write `python discrimy.py` in a terminal I get  `ImportError: No module named 'discord'` 
Here's the full error message: 
```
Traceback (most recent call last):
  File "discrimy.py", line 32, in <module>
    import discord
ImportError: No module named 'discord'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "discrimy.py", line 35, in <module>
    import discord
ImportError: No module named 'discord'
```
Also, should I disable 2FA ? I think that you should really make a INSTALLATION.md for your project. 
I hope you will be able to help me, thank you in advance!

**Comment by Gamerhythm** [comment]
Are you on the latest update? You do not need to disable 2FA. 
Thanks,
Jake

**Comment by deatcoca** [comment]
Well, I was using this release:  https://github.com/Gamerhythm/Discrimy/releases/tag/Discrimy
I disabled 2FA and wrote `python3 discrimy.py` and I saw the `[INFO] Signing into Discord. This may take a while.` line. So it should be working. But after 20 min nothing happened, is this normal ?

**Comment by Gamerhythm** [comment]
If you can, try doing python3.5 discrimy.py - that should run it through Python 3.5

**Comment by Gamerhythm** [comment]
If you don't have Python 3.5 installed, you will need to install it.

**Comment by Gamerhythm** [comment]
If it takes a while then, it is probably down to either your computer or your connection. Give it some time and it will connect.

**Comment by deatcoca** [comment]
Okay, my version of python is `Python 3.5.3` so no problem. And I'll try to wait. Thank you for your answers!
